// IR loader - read-only access to ModelFile FlatBuffers (schemas/ir.fbs).
//
// The loader validates and owns the buffer, then exposes the generated
// `logicpilot::ir::ModelFile` view (zero-copy, no mutation - contract F1).
// build_replication_model() lowers an executable model for the kinds the
// Phase 1b kernel can run today:
//   * ProcessModel (source -> queue -> service -> sink) -> QueueingFlowSim
// AtomicModel / CoupledModel IR is readable/inspectable but not executable
// yet: their TransitionSpec handlers are lowered by later compiler phases.
#pragma once

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "logicpilot/devs/replication.h"

namespace logicpilot {
namespace ir {
struct ModelFile;  // generated by flatc into ir_generated.h
}

enum class IrStatus {
  kOk,
  kIoError,             // file not readable
  kCorruptBuffer,       // verifier rejected the buffer
  kBadSchemaVersion,    // schema_version != 1 (F1)
  kMissingRoot,         // ModelFile.root absent
  kUnsupportedKind,     // model kind has no executable lowering yet
  kInvalidStructure,    // nodes/couplings don't form a runnable flow
};

[[nodiscard]] const char* to_string(IrStatus status);

// Loaded, verified ModelFile. `root` is a zero-copy view into `bytes`.
struct IrModelFile {
  std::vector<std::uint8_t> bytes;
  const ir::ModelFile* root{nullptr};
};

struct IrLoadResult {
  IrStatus status{IrStatus::kOk};
  std::string message;
  IrModelFile file;

  [[nodiscard]] bool ok() const { return status == IrStatus::kOk; }
};

// Load + verify from a file path (.lpir, file_identifier "LPIR").
IrLoadResult load_model_file(const std::string& path);

// Load + verify from an in-memory buffer (buffer is copied).
IrLoadResult load_model_buffer(const std::uint8_t* data, std::size_t size);

// Human-readable description of the root model (name, kind, child counts).
std::string inspect_model(const IrModelFile& file);

// Lower an executable replication model from the loaded IR. Returns nullptr
// (with `error` filled) when the kind has no Phase 1b lowering.
std::unique_ptr<ReplicationModel> build_replication_model(
    const IrModelFile& file, std::string* error = nullptr);

}  // namespace logicpilot
