// IR loader - read-only access to the v2 ModelFile FlatBuffers
// (schemas/ir_v2.fbs, file_identifier "LP2R").
//
// The loader validates and owns the buffer, then exposes the generated
// `logicpilot::ir::v2::ModelFile` view (zero-copy, no mutation).
// build_replication_model() lowers an executable model for the kinds the
// kernel can run (all v2-native):
//   * process flow (stages + couplings) -> QueueingFlowSim / ProcessFlowSim
//   * devs/atomic tree       -> DevsReplicationModel
//   * agent tree             -> AgentReplicationModel
//   * sd/equation node       -> ContinuousReplicationModel
#pragma once

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "logicpilot/devs/replication.h"

namespace logicpilot {
namespace ir::v2 {
struct ModelFile;  // generated by flatc into ir_v2_generated.h
}

enum class IrStatus {
  kOk,
  kIoError,             // file not readable
  kCorruptBuffer,       // verifier rejected the buffer
    kBadSchemaVersion,    // schema_version != 2
    kMissingRoot,         // ModelFile.root absent
    kUnsupportedKind,     // root block has no executable lowering yet
    kInvalidStructure,    // nodes/couplings don't form a runnable flow
};

[[nodiscard]] const char* to_string(IrStatus status);

// Loaded, verified v2 ModelFile. `v2_root` is a zero-copy view into
// `v2_bytes`. Move-only: copying would deep-copy the buffer while the
// pointer kept pointing into the source buffer, leaving a dangling root.
struct IrModelFile {
  std::vector<std::uint8_t> v2_bytes;
  const ir::v2::ModelFile* v2_root{nullptr};

  IrModelFile() = default;
  IrModelFile(const IrModelFile&) = delete;
  IrModelFile& operator=(const IrModelFile&) = delete;
  IrModelFile(IrModelFile&&) = default;
  IrModelFile& operator=(IrModelFile&&) = default;
};

struct IrLoadResult {
  IrStatus status{IrStatus::kOk};
  std::string message;
  IrModelFile file;

  [[nodiscard]] bool ok() const { return status == IrStatus::kOk; }
};

// Load + verify from a file path (.lpir, file_identifier "LP2R").
IrLoadResult load_model_file(const std::string& path);

// Load + verify from an in-memory buffer (buffer is copied).
IrLoadResult load_model_buffer(const std::uint8_t* data, std::size_t size);

// Human-readable description of the root model (name, kind, child counts).
std::string inspect_model(const IrModelFile& file);

// Resolve the set of modeling methods present in the model (root semantics
// plus child libraries, e.g. process / statechart / devs / agent / sd).
// Returns an empty vector when nothing executable is present. The
// SimulationKernel driver attaches one runtime per method so multi-method
// models compose through a shared kernel scheduler.
std::vector<std::string> resolve_method_names(const IrModelFile& file);

struct MethodRequirement {
  std::string method;
  // Distinct SemanticsRef.version values requested by nodes of this method.
  // An empty string represents legacy/unversioned semantics.
  std::vector<std::string> semantics_versions;
};

// Version-aware form used by SimulationKernel and future plugin loaders.
std::vector<MethodRequirement> resolve_method_requirements(
    const IrModelFile& file);

// Lower an executable replication model from the loaded IR. Returns nullptr
// (with `error` filled) when the kind has no Phase 1b lowering.
std::unique_ptr<ReplicationModel> build_replication_model(
    const IrModelFile& file, std::string* error = nullptr);

// Exponential-flow run parameters for the streaming driver (lp-server).
struct FlowRunParams {
  double lambda{0.0};
  double mu{0.0};
  std::int64_t servers{1};
  double failure_rate{0.0};
  double repair_rate{1.0};
};

// Extracts the exponential-flow parameters from a (coupled) ProcessModel:
// arrival rate (poisson/exponential), service rate (exponential), server
// count and the resource's failure/repair rates. Returns false when the
// model is not a single-source/single-service exponential flow (a
// limitation of the streaming driver), with `error` filled.
bool extract_flow_params(const IrModelFile& file, FlowRunParams& out,
                         std::string* error = nullptr);

}  // namespace logicpilot
