// Parser front end implementation: tree-sitter parse + cursor-based AST
// extraction (see include/logicpilot/dsl/parser.h).
#include "logicpilot/dsl/parser.h"

#include <algorithm>
#include <cerrno>
#include <cstdlib>
#include <cstring>

#include <tree_sitter/api.h>

extern "C" {
// Entry point of the checked-in grammar (dsl/tree-sitter-logicpilot,
// ADR-0005; ABI 15, generated by tree-sitter CLI 0.26.11).
const TSLanguage* tree_sitter_logicpilot(void);
}

namespace logicpilot::dsl {
namespace {

// ---------------------------------------------------------------------------
// Node helpers
// ---------------------------------------------------------------------------

Span span_of(const TSNode& node) {
  Span span;
  const TSPoint start = ts_node_start_point(node);
  span.line = start.row + 1;        // tree-sitter is 0-based
  span.column = start.column + 1;
  span.byte_offset = ts_node_start_byte(node);
  span.byte_length = ts_node_end_byte(node) - ts_node_start_byte(node);
  return span;
}

bool node_is(const TSNode& node, const char* type) {
  return std::strcmp(ts_node_type(node), type) == 0;
}

TSNode field(const TSNode& node, const char* name) {
  return ts_node_child_by_field_name(
      node, name, static_cast<uint32_t>(std::strlen(name)));
}

// Cursor-based iteration over the direct named children of `node` (comments
// are extras and are skipped). `fn` receives each child TSNode.
template <typename Fn>
void each_named_child(const TSNode& node, Fn&& fn) {
  TSTreeCursor cursor = ts_tree_cursor_new(node);
  if (ts_tree_cursor_goto_first_child(&cursor) > 0) {
    do {
      const TSNode child = ts_tree_cursor_current_node(&cursor);
      if (ts_node_is_named(child) && !node_is(child, "comment")) {
        fn(child);
      }
    } while (ts_tree_cursor_goto_next_sibling(&cursor) > 0);
  }
  ts_tree_cursor_delete(&cursor);
}

// ---------------------------------------------------------------------------
// Syntax error collection (cursor DFS; stops descending into ERROR nodes)
// ---------------------------------------------------------------------------

void collect_syntax_errors(const TSNode& node, const std::string& source,
                           std::vector<Diagnostic>& out) {
  if (ts_node_is_error(node) || ts_node_is_missing(node)) {
    Diagnostic diagnostic;
    diagnostic.severity = Severity::kError;
    diagnostic.code = "LP0001";
    diagnostic.span = span_of(node);
    if (ts_node_is_missing(node)) {
      diagnostic.message =
          std::string("syntax error: missing '") + ts_node_type(node) + "'";
    } else {
      const uint32_t start = ts_node_start_byte(node);
      const uint32_t end = ts_node_end_byte(node);
      std::string snippet = source.substr(start, std::min(end - start, 24u));
      if (snippet.empty()) {
        snippet = ts_node_type(node);
      }
      diagnostic.message = "syntax error near '" + snippet + "'";
    }
    out.push_back(std::move(diagnostic));
    return;  // do not descend; one diagnostic per error region
  }
  TSTreeCursor cursor = ts_tree_cursor_new(node);
  if (ts_tree_cursor_goto_first_child(&cursor) > 0) {
    do {
      collect_syntax_errors(ts_tree_cursor_current_node(&cursor), source, out);
    } while (ts_tree_cursor_goto_next_sibling(&cursor) > 0);
  }
  ts_tree_cursor_delete(&cursor);
}

// ---------------------------------------------------------------------------
// AST extraction
// ---------------------------------------------------------------------------

class Extractor {
 public:
  Extractor(const std::string& source, std::vector<Diagnostic>& diagnostics)
      : source_(source), diagnostics_(diagnostics) {}

  bool extract_model(const TSNode& root, ModelAst& out) {
    // source_file = a single model_declaration (grammar R1). Comments are
    // named extras, so the first *non-comment* named child is the model.
    TSNode model = root;
    if (node_is(root, "source_file")) {
      model = TSNode{};
      each_named_child(root, [&](const TSNode& child) {
        if (ts_node_is_null(model)) {
          model = child;
        }
      });
      if (ts_node_is_null(model) || !node_is(model, "model_declaration")) {
        error(root, "LP0001", "syntax error: expected a model declaration");
        return false;
      }
    }
    if (!node_is(model, "model_declaration")) {
      error(model, "LP0001", "syntax error: expected a model declaration");
      return false;
    }
    out.span = span_of(model);
    const TSNode name = field(model, "name");
    out.name = text_of(name);
    out.name_span = span_of(name);

    const TSNode body = field(model, "body");
    each_named_child(body, [&](const TSNode& member) {
      if (node_is(member, "resource_declaration")) {
        out.resources.push_back(extract_resource(member));
      } else if (node_is(member, "process_declaration")) {
        out.processes.push_back(extract_process(member));
      } else if (node_is(member, "atomic_declaration")) {
        out.atomics.push_back(extract_atomic(member));
      } else if (node_is(member, "agent_declaration")) {
        out.agents.push_back(extract_agent(member));
      } else if (node_is(member, "experiment_declaration")) {
        out.experiments.push_back(extract_experiment(member));
      } else if (node_is(member, "couple_declaration")) {
        out.couplings.push_back(extract_couple(member));
      }
    });
    return true;
  }

 private:
  std::string text_of(const TSNode& node) const {
    const uint32_t start = ts_node_start_byte(node);
    const uint32_t end = ts_node_end_byte(node);
    return source_.substr(start, end - start);
  }

  void error(const TSNode& at, const char* code, const std::string& message) {
    Diagnostic diagnostic;
    diagnostic.severity = Severity::kError;
    diagnostic.code = code;
    diagnostic.message = message;
    diagnostic.span = span_of(at);
    diagnostics_.push_back(std::move(diagnostic));
  }

  bool integer_of(const TSNode& node, std::int64_t& out) {
    const std::string text = text_of(node);
    errno = 0;
    char* end = nullptr;
    const long long value = std::strtoll(text.c_str(), &end, 10);
    if (errno == ERANGE || end != text.c_str() + text.size()) {
      error(node, "LP3001",
            "integer literal '" + text + "' is out of range");
      return false;
    }
    out = value;
    return true;
  }

  bool double_of(const TSNode& node, double& out) {
    const std::string text = text_of(node);
    errno = 0;
    char* end = nullptr;
    const double value = std::strtod(text.c_str(), &end);
    if (errno == ERANGE || end != text.c_str() + text.size()) {
      error(node, "LP3001",
            "numeric literal '" + text + "' is out of range");
      return false;
    }
    out = value;
    return true;
  }

  bool param_of(const TSNode& call, const char* field_name, double& out) {
    const TSNode value = field(call, field_name);
    return !ts_node_is_null(value) && double_of(value, out);
  }

  // value_literal -> AtomicValue (bool / int / float literal).
  AtomicValue extract_value(const TSNode& literal) {
    AtomicValue value;
    value.span = span_of(literal);
    const TSNode token = ts_node_named_child(literal, 0);
    if (node_is(token, "boolean_literal")) {
      value.kind = AtomicValueKind::kBool;
      value.bool_value = text_of(token) == "true";
    } else if (node_is(token, "integer")) {
      value.kind = AtomicValueKind::kInt;
      integer_of(token, value.int_value);
    } else if (node_is(token, "float")) {
      value.kind = AtomicValueKind::kFloat;
      double_of(token, value.float_value);
    }
    return value;
  }

  void extract_effects(const TSNode& effects_node, TransitionDecl& out) {
    each_named_child(effects_node, [&](const TSNode& effect_node) {
      if (!node_is(effect_node, "effect")) {
        return;
      }
      Effect effect;
      const TSNode name = field(effect_node, "name");
      effect.name = text_of(name);
      effect.name_span = span_of(name);
      effect.value = extract_value(field(effect_node, "value"));
      out.effects.push_back(std::move(effect));
    });
  }

  AtomicDecl extract_atomic(const TSNode& decl) {
    AtomicDecl atomic;
    atomic.span = span_of(decl);
    const TSNode name = field(decl, "name");
    atomic.name = text_of(name);
    atomic.name_span = span_of(name);
    const TSNode body = field(decl, "body");
    each_named_child(body, [&](const TSNode& field_node) {
      if (node_is(field_node, "state_field")) {
        StateVarDecl var;
        const TSNode var_name = field(field_node, "name");
        var.name = text_of(var_name);
        var.name_span = span_of(var_name);
        var.value = extract_value(field(field_node, "value"));
        atomic.state.push_back(std::move(var));
      } else if (node_is(field_node, "time_advance_field")) {
        atomic.ta.has = true;
        atomic.ta.count += 1;
        atomic.ta.span = span_of(field_node);
        const TSNode expr = field(field_node, "value");
        const TSNode call = ts_node_named_child(expr, 0);
        if (node_is(call, "constant_call")) {
          atomic.ta.kind = TaKind::kConstant;
          param_of(call, "value", atomic.ta.value);
        } else if (node_is(call, "exponential_call")) {
          atomic.ta.kind = TaKind::kExponential;
          param_of(call, "rate", atomic.ta.value);
        } else if (node_is(call, "infinite_literal")) {
          atomic.ta.kind = TaKind::kInfinite;
        } else {
          // Bare number literal.
          atomic.ta.kind = TaKind::kConstant;
          double_of(call, atomic.ta.value);
        }
      } else if (node_is(field_node, "on_input_field")) {
        TransitionDecl transition;
        transition.has = true;
        transition.count += 1;
        transition.span = span_of(field_node);
        const TSNode port = field(field_node, "port");
        transition.port = text_of(port);
        transition.port_span = span_of(port);
        extract_effects(field(field_node, "effects"), transition);
        atomic.on_input.push_back(std::move(transition));
      } else if (node_is(field_node, "on_timeout_field")) {
        atomic.on_timeout.has = true;
        atomic.on_timeout.count += 1;
        atomic.on_timeout.span = span_of(field_node);
        const TSNode effects = field(field_node, "effects");
        if (!ts_node_is_null(effects)) {
          extract_effects(effects, atomic.on_timeout);
        }
        const TSNode emit_port = field(field_node, "port");
        if (!ts_node_is_null(emit_port)) {
          atomic.on_timeout.emit = true;
          atomic.on_timeout.emit_port = text_of(emit_port);
          atomic.on_timeout.emit_span = span_of(emit_port);
        }
      }
    });
    return atomic;
  }

  CoupleDecl extract_couple(const TSNode& decl) {
    CoupleDecl couple;
    couple.span = span_of(decl);
    couple.from_model = text_of(field(decl, "from_model"));
    couple.from_port = text_of(field(decl, "from_port"));
    couple.to_model = text_of(field(decl, "to_model"));
    couple.to_port = text_of(field(decl, "to_port"));
    return couple;
  }

  AgentDecl extract_agent(const TSNode& decl) {
    AgentDecl agent;
    agent.span = span_of(decl);
    const TSNode name = field(decl, "name");
    agent.name = text_of(name);
    agent.name_span = span_of(name);
    const TSNode body = field(decl, "body");
    each_named_child(body, [&](const TSNode& field_node) {
      if (node_is(field_node, "count_field")) {
        agent.has_count = true;
        agent.count_count += 1;
        agent.count_field_span = span_of(field_node);
        std::int64_t value = 0;
        if (integer_of(field(field_node, "value"), value)) {
          agent.count = value;
        }
      } else if (node_is(field_node, "state_field")) {
        StateVarDecl var;
        const TSNode var_name = field(field_node, "name");
        var.name = text_of(var_name);
        var.name_span = span_of(var_name);
        var.value = extract_value(field(field_node, "value"));
        agent.state.push_back(std::move(var));
      } else if (node_is(field_node, "on_tick_field")) {
        TickBehavior behavior;
        behavior.has = true;
        behavior.count += 1;
        behavior.span = span_of(field_node);
        const TSNode handler = field(field_node, "handler");
        behavior.handler = text_of(handler);
        behavior.handler_span = span_of(handler);
        const TSNode arg = field(field_node, "arg");
        if (!ts_node_is_null(arg)) {
          behavior.has_arg = true;
          behavior.arg = text_of(arg);
          behavior.arg_span = span_of(arg);
        }
        agent.behaviors.push_back(std::move(behavior));
      }
    });
    return agent;
  }

  ExperimentDecl extract_experiment(const TSNode& decl) {
    ExperimentDecl experiment;
    experiment.span = span_of(decl);
    const TSNode name = field(decl, "name");
    experiment.name = text_of(name);
    experiment.name_span = span_of(name);
    const TSNode body = field(decl, "body");
    each_named_child(body, [&](const TSNode& field_node) {
      const auto string_field = [&](const char* f) {
        return text_of(field(field_node, f));
      };
      if (node_is(field_node, "objective_field")) {
        experiment.has_objective = true;
        experiment.objective_count += 1;
        experiment.objective = string_field("value");
        experiment.objective_span = span_of(field(field_node, "value"));
      } else if (node_is(field_node, "metric_field")) {
        experiment.has_metric = true;
        experiment.metric_count += 1;
        experiment.metric = string_field("value");
        experiment.metric_span = span_of(field(field_node, "value"));
      } else if (node_is(field_node, "variable_field")) {
        experiment.has_variable = true;
        experiment.variable_count += 1;
        experiment.variable = string_field("value");
        experiment.variable_span = span_of(field(field_node, "value"));
      } else if (node_is(field_node, "range_field")) {
        experiment.has_range = true;
        experiment.range_count += 1;
        experiment.range_span = span_of(field_node);
        std::int64_t min = 0;
        std::int64_t max = 0;
        if (integer_of(field(field_node, "min"), min)) {
          experiment.range_min = min;
        }
        if (integer_of(field(field_node, "max"), max)) {
          experiment.range_max = max;
        }
      } else if (node_is(field_node, "budget_field")) {
        experiment.has_budget = true;
        experiment.budget_count += 1;
        experiment.budget_span = span_of(field(field_node, "value"));
        std::int64_t value = 0;
        if (integer_of(field(field_node, "value"), value)) {
          experiment.budget = value;
        }
      }
    });
    return experiment;
  }

  // arrival_expr / service_time_expr -> Distribution.
  bool distribution_of(const TSNode& expr, Distribution& out) {
    out.span = span_of(expr);
    const TSNode call = ts_node_named_child(expr, 0);
    if (ts_node_is_null(call)) {
      error(expr, "LP0001", "syntax error: expected a distribution call");
      return false;
    }
    if (node_is(call, "poisson_call")) {
      out.kind = DistKind::kPoisson;
      double rate = 0.0;
      if (!param_of(call, "rate", rate)) return false;
      out.params.push_back(rate);
      return true;
    }
    if (node_is(call, "exponential_call")) {
      out.kind = DistKind::kExponential;
      double rate = 0.0;
      if (!param_of(call, "rate", rate)) return false;
      out.params.push_back(rate);
      return true;
    }
    if (node_is(call, "normal_call")) {
      out.kind = DistKind::kNormal;
      double mean = 0.0;
      double stddev = 0.0;
      if (!param_of(call, "mean", mean) ||
          !param_of(call, "stddev", stddev)) {
        return false;
      }
      out.params.push_back(mean);
      out.params.push_back(stddev);
      return true;
    }
    if (node_is(call, "constant_call")) {
      out.kind = DistKind::kConstant;
      double value = 0.0;
      if (!param_of(call, "value", value)) return false;
      out.params.push_back(value);
      return true;
    }
    error(call, "LP0001",
          std::string("unknown distribution '") + ts_node_type(call) + "'");
    return false;
  }

  ResourceDecl extract_resource(const TSNode& decl) {
    ResourceDecl resource;
    resource.span = span_of(decl);
    const TSNode name = field(decl, "name");
    resource.name = text_of(name);
    resource.name_span = span_of(name);
    const TSNode body = field(decl, "body");
    each_named_child(body, [&](const TSNode& field_node) {
      if (node_is(field_node, "capacity_field")) {
        resource.capacity_count += 1;
        resource.capacity_field_span = span_of(field_node);
        std::int64_t value = 0;
        if (integer_of(field(field_node, "value"), value)) {
          resource.has_capacity = true;
          resource.capacity = value;
        }
      } else if (node_is(field_node, "failure_rate_field")) {
        resource.failure_rate_count += 1;
        resource.failure_rate_field_span = span_of(field_node);
        double value = 0.0;
        if (double_of(field(field_node, "value"), value)) {
          resource.has_failure_rate = true;
          resource.failure_rate = value;
        }
      }
    });
    return resource;
  }

  StageDecl extract_stage(const TSNode& decl) {
    StageDecl stage;
    stage.span = span_of(decl);
    const TSNode name = field(decl, "name");
    stage.name = text_of(name);
    stage.name_span = span_of(name);
    const TSNode body = field(decl, "body");

    if (node_is(decl, "source_declaration")) {
      stage.kind = StageDecl::Kind::kSource;
      each_named_child(body, [&](const TSNode& field_node) {
        if (node_is(field_node, "arrival_field")) {
          stage.arrival_count += 1;
          stage.arrival_field_span = span_of(field_node);
          Distribution arrival;
          if (distribution_of(field(field_node, "value"), arrival)) {
            stage.has_arrival = true;
            stage.arrival = std::move(arrival);
          }
        }
      });
    } else if (node_is(decl, "queue_declaration")) {
      stage.kind = StageDecl::Kind::kQueue;
      each_named_child(body, [&](const TSNode& field_node) {
        if (node_is(field_node, "capacity_field")) {
          stage.capacity_count += 1;
          stage.capacity_field_span = span_of(field_node);
          std::int64_t value = 0;
          if (integer_of(field(field_node, "value"), value)) {
            stage.has_capacity = true;
            stage.capacity = value;
          }
        }
      });
    } else if (node_is(decl, "service_declaration")) {
      stage.kind = StageDecl::Kind::kService;
      each_named_child(body, [&](const TSNode& field_node) {
        if (node_is(field_node, "time_field")) {
          stage.time_count += 1;
          stage.time_field_span = span_of(field_node);
          Distribution service_time;
          if (distribution_of(field(field_node, "value"), service_time)) {
            stage.has_time = true;
            stage.service_time = std::move(service_time);
          }
        }
      });
    }
    return stage;
  }

  ProcessDecl extract_process(const TSNode& decl) {
    ProcessDecl process;
    process.span = span_of(decl);
    const TSNode name = field(decl, "name");
    process.name = text_of(name);
    process.name_span = span_of(name);
    const TSNode body = field(decl, "body");
    each_named_child(body, [&](const TSNode& stage_node) {
      if (node_is(stage_node, "source_declaration") ||
          node_is(stage_node, "queue_declaration") ||
          node_is(stage_node, "service_declaration")) {
        process.stages.push_back(extract_stage(stage_node));
      }
    });
    return process;
  }

  const std::string& source_;
  std::vector<Diagnostic>& diagnostics_;
};

}  // namespace

const char* to_string(DistKind kind) {
  switch (kind) {
    case DistKind::kPoisson: return "poisson";
    case DistKind::kExponential: return "exponential";
    case DistKind::kNormal: return "normal";
    case DistKind::kConstant: return "constant";
  }
  return "unknown";
}

ParseOutput parse_source(const std::string& source, const std::string& path) {
  ParseOutput output;

  TSParser* parser = ts_parser_new();
  ts_parser_set_language(parser, tree_sitter_logicpilot());
  TSTree* tree = ts_parser_parse_string(
      parser, nullptr, source.c_str(), static_cast<uint32_t>(source.size()));
  ts_parser_delete(parser);

  if (tree == nullptr) {
    Diagnostic diagnostic;
    diagnostic.severity = Severity::kError;
    diagnostic.code = "LP0001";
    diagnostic.message = "syntax error: parser produced no tree";
    output.diagnostics.push_back(std::move(diagnostic));
    return output;
  }

  const TSNode root = ts_tree_root_node(tree);
  collect_syntax_errors(root, source, output.diagnostics);
  if (!output.diagnostics.empty()) {
    ts_tree_delete(tree);
    return output;
  }

  ModelAst model;
  Extractor extractor{source, output.diagnostics};
  if (extractor.extract_model(root, model) && output.diagnostics.empty()) {
    output.model = std::move(model);
  }
  ts_tree_delete(tree);
  (void)path;  // spans are path-relative; lpcli renders them with the path
  return output;
}

}  // namespace logicpilot::dsl
