// Parser front end implementation: tree-sitter parse + cursor-based AST
// extraction (see include/logicpilot/dsl/parser.h).
//
// The grammar is the thin v2 skeleton (docs/specs/dsl-v2.md): every
// declaration is `kind name { ... }` with a generic body, so the extractor
// walks one generic `Node` tree and lets the semantic analyzer resolve
// kinds against the core kinds + library registry.
#include "logicpilot/dsl/parser.h"

#include <algorithm>
#include <cctype>
#include <cerrno>
#include <cstdlib>
#include <cstring>

#include <tree_sitter/api.h>

extern "C" {
// Entry point of the checked-in grammar (dsl/tree-sitter-logicpilot,
// ADR-0005; ABI 15, generated by tree-sitter CLI 0.26.11).
const TSLanguage* tree_sitter_logicpilot(void);
}

namespace logicpilot::dsl {
namespace {

// ---------------------------------------------------------------------------
// Node helpers
// ---------------------------------------------------------------------------

Span span_of(const TSNode& node) {
  Span span;
  const TSPoint start = ts_node_start_point(node);
  span.line = start.row + 1;        // tree-sitter is 0-based
  span.column = start.column + 1;
  span.byte_offset = ts_node_start_byte(node);
  span.byte_length = ts_node_end_byte(node) - ts_node_start_byte(node);
  return span;
}

bool node_is(const TSNode& node, const char* type) {
  return std::strcmp(ts_node_type(node), type) == 0;
}

TSNode field(const TSNode& node, const char* name) {
  return ts_node_child_by_field_name(
      node, name, static_cast<uint32_t>(std::strlen(name)));
}

// Cursor-based iteration over the direct named children of `node` (comments
// are extras and are skipped). `fn` receives each child TSNode.
template <typename Fn>
void each_named_child(const TSNode& node, Fn&& fn) {
  TSTreeCursor cursor = ts_tree_cursor_new(node);
  if (ts_tree_cursor_goto_first_child(&cursor) > 0) {
    do {
      const TSNode child = ts_tree_cursor_current_node(&cursor);
      if (ts_node_is_named(child) && !node_is(child, "comment")) {
        fn(child);
      }
    } while (ts_tree_cursor_goto_next_sibling(&cursor) > 0);
  }
  ts_tree_cursor_delete(&cursor);
}

// ---------------------------------------------------------------------------
// Syntax error collection (cursor DFS; stops descending into ERROR nodes)
// ---------------------------------------------------------------------------

void collect_syntax_errors(const TSNode& node, const std::string& source,
                           std::vector<Diagnostic>& out) {
  if (ts_node_is_error(node) || ts_node_is_missing(node)) {
    Diagnostic diagnostic;
    diagnostic.severity = Severity::kError;
    diagnostic.code = "LP0001";
    diagnostic.span = span_of(node);
    if (ts_node_is_missing(node)) {
      diagnostic.message =
          std::string("syntax error: missing '") + ts_node_type(node) + "'";
    } else {
      const uint32_t start = ts_node_start_byte(node);
      const uint32_t end = ts_node_end_byte(node);
      std::string snippet = source.substr(start, std::min(end - start, 24u));
      if (snippet.empty()) {
        snippet = ts_node_type(node);
      }
      diagnostic.message = "syntax error near '" + snippet + "'";
    }
    out.push_back(std::move(diagnostic));
    return;  // do not descend; one diagnostic per error region
  }
  TSTreeCursor cursor = ts_tree_cursor_new(node);
  if (ts_tree_cursor_goto_first_child(&cursor) > 0) {
    do {
      collect_syntax_errors(ts_tree_cursor_current_node(&cursor), source, out);
    } while (ts_tree_cursor_goto_next_sibling(&cursor) > 0);
  }
  ts_tree_cursor_delete(&cursor);
}

// ---------------------------------------------------------------------------
// AST extraction
// ---------------------------------------------------------------------------

class Extractor {
 public:
  Extractor(const std::string& source, std::vector<Diagnostic>& diagnostics)
      : source_(source), diagnostics_(diagnostics) {}

  bool extract_model(const TSNode& root, ModelAst& out) {
    // source_file = a single model_declaration. Comments are named extras,
    // so the first *non-comment* named child is the model.
    TSNode model = root;
    if (node_is(root, "source_file")) {
      model = TSNode{};
      each_named_child(root, [&](const TSNode& child) {
        if (ts_node_is_null(model)) {
          model = child;
        }
      });
      if (ts_node_is_null(model) || !node_is(model, "model_declaration")) {
        error(root, "LP0001", "syntax error: expected a model declaration");
        return false;
      }
    }
    if (!node_is(model, "model_declaration")) {
      error(model, "LP0001", "syntax error: expected a model declaration");
      return false;
    }
    out.span = span_of(model);
    const TSNode name = field(model, "name");
    out.name = text_of(name);
    out.name_span = span_of(name);

    const TSNode body = field(model, "body");
    each_named_child(body, [&](const TSNode& member) {
      if (node_is(member, "use_declaration")) {
        out.used_libraries.push_back(text_of(field(member, "library")));
      } else if (node_is(member, "variable_declaration")) {
        out.params.push_back(extract_var_decl(member));
      } else if (node_is(member, "couple_declaration")) {
        out.couplings.push_back(extract_couple(member));
      } else if (node_is(member, "declaration")) {
        Node node = extract_node(member);
        if (node.kind == "experiment") {
          out.experiments.push_back(extract_experiment(node));
        }
        out.members.push_back(std::move(node));
      }
    });
    return true;
  }

 private:
  std::string text_of(const TSNode& node) const {
    const uint32_t start = ts_node_start_byte(node);
    const uint32_t end = ts_node_end_byte(node);
    return source_.substr(start, end - start);
  }

  void error(const TSNode& at, const char* code, const std::string& message) {
    Diagnostic diagnostic;
    diagnostic.severity = Severity::kError;
    diagnostic.code = code;
    diagnostic.message = message;
    diagnostic.span = span_of(at);
    diagnostics_.push_back(std::move(diagnostic));
  }

  bool integer_of(const TSNode& node, std::int64_t& out) {
    const std::string text = text_of(node);
    errno = 0;
    char* end = nullptr;
    const long long value = std::strtoll(text.c_str(), &end, 10);
    if (errno == ERANGE || end != text.c_str() + text.size()) {
      error(node, "LP3001",
            "integer literal '" + text + "' is out of range");
      return false;
    }
    out = value;
    return true;
  }

  bool double_of(const TSNode& node, double& out) {
    const std::string text = text_of(node);
    errno = 0;
    char* end = nullptr;
    const double value = std::strtod(text.c_str(), &end);
    if (errno == ERANGE || end != text.c_str() + text.size()) {
      error(node, "LP3001",
            "numeric literal '" + text + "' is out of range");
      return false;
    }
    out = value;
    return true;
  }

  // First word of a node's source text (keyword tokens are anonymous, e.g.
  // the `state`/`param`/`in`/`out` prefixes of variable/port declarations).
  std::string first_word_of(const TSNode& node) const {
    const std::string text = text_of(node);
    std::size_t end = 0;
    while (end < text.size() &&
           (std::isalnum(static_cast<unsigned char>(text[end])) ||
            text[end] == '_')) {
      ++end;
    }
    return text.substr(0, end);
  }

  // value -> Value expression tree (literal / identifier / call /
  // arithmetic).
  Value extract_value(const TSNode& node) {
    Value value;
    value.span = span_of(node);
    const TSNode child = ts_node_named_child(node, 0);
    if (node_is(child, "value_literal")) {
      const TSNode token = ts_node_named_child(child, 0);
      if (node_is(token, "boolean_literal")) {
        value.kind = ValueKind::kBool;
        value.bool_value = text_of(token) == "true";
      } else if (node_is(token, "integer")) {
        value.kind = ValueKind::kInt;
        integer_of(token, value.int_value);
      } else if (node_is(token, "float")) {
        value.kind = ValueKind::kFloat;
        double_of(token, value.float_value);
      } else if (node_is(token, "string_literal")) {
        value.kind = ValueKind::kString;
        std::string text = text_of(token);
        if (text.size() >= 2) {
          text = text.substr(1, text.size() - 2);  // strip quotes
        }
        value.string_value = text;
      }
    } else if (node_is(child, "identifier")) {
      value.kind = ValueKind::kIdentifier;
      value.string_value = text_of(child);
    } else if (node_is(child, "call")) {
      value.kind = ValueKind::kCall;
      value.call_name = text_of(field(child, "name"));
      const TSNode args = field(child, "args");
      each_named_child(args, [&](const TSNode& arg_node) {
        value.call_args.push_back(extract_value(arg_node));
      });
    } else if (node_is(child, "binary_expression")) {
      const std::string op = text_of(field(child, "op"));
      value.kind = op == "+" ? ValueKind::kAdd
                  : op == "-" ? ValueKind::kSub
                  : op == "*" ? ValueKind::kMul
                              : ValueKind::kDiv;
      value.operands.push_back(extract_value(field(child, "left")));
      value.operands.push_back(extract_value(field(child, "right")));
    } else if (node_is(child, "unary_expression")) {
      value.kind = ValueKind::kNegate;
      value.operands.push_back(extract_value(field(child, "operand")));
    } else if (node_is(child, "parenthesized_expression")) {
      value.kind = ValueKind::kParen;
      value.operands.push_back(extract_value(field(child, "value")));
    }
    return value;
  }

  Field extract_field(const TSNode& node) {
    Field out;
    out.span = span_of(node);
    out.name = text_of(field(node, "name"));
    out.name_span = span_of(field(node, "name"));
    out.value = extract_value(field(node, "value"));
    return out;
  }

  RangeField extract_range(const TSNode& node) {
    RangeField range;
    range.span = span_of(node);
    std::int64_t value = 0;
    if (integer_of(field(node, "min"), value)) {
      range.min = value;
    }
    if (integer_of(field(node, "max"), value)) {
      range.max = value;
    }
    return range;
  }

  VarDecl extract_var_decl(const TSNode& node) {
    VarDecl var;
    var.span = span_of(node);
    var.keyword = first_word_of(node);
    var.name = text_of(field(node, "name"));
    var.name_span = span_of(field(node, "name"));
    const TSNode type = field(node, "type");
    if (!ts_node_is_null(type)) {
      var.type = text_of(type);
    }
    var.value = extract_value(field(node, "value"));
    return var;
  }

  PortDecl extract_port(const TSNode& node) {
    PortDecl port;
    port.span = span_of(node);
    port.direction = first_word_of(node);
    const TSNode name = field(node, "name");
    if (!ts_node_is_null(name)) {
      port.name = text_of(name);
    }
    port.type = text_of(field(node, "type"));
    return port;
  }

  Effect extract_effect(const TSNode& node) {
    Effect effect;
    const TSNode child = ts_node_named_child(node, 0);
    if (node_is(child, "assignment_effect")) {
      effect.kind = Effect::Kind::kAssign;
      effect.name = text_of(field(child, "name"));
      effect.name_span = span_of(field(child, "name"));
      effect.value = extract_value(field(child, "value"));
    } else if (node_is(child, "emit_effect")) {
      effect.kind = Effect::Kind::kEmit;
      effect.name = text_of(field(child, "port"));
      effect.name_span = span_of(field(child, "port"));
    } else if (node_is(child, "call_effect")) {
      effect.kind = Effect::Kind::kCall;
      effect.name = text_of(field(child, "handler"));
      effect.name_span = span_of(field(child, "handler"));
      const TSNode arg = field(child, "arg");
      if (!ts_node_is_null(arg)) {
        effect.arg = text_of(arg);
        effect.arg_span = span_of(arg);
      }
    }
    return effect;
  }

  Behavior extract_behavior(const TSNode& node) {
    Behavior behavior;
    behavior.span = span_of(node);
    std::string trigger = text_of(field(node, "trigger"));
    // Strip the `on_` prefix (on_timeout -> timeout).
    if (trigger.rfind("on_", 0) == 0) {
      trigger = trigger.substr(3);
    }
    behavior.trigger = trigger;
    const TSNode port = field(node, "port");
    if (!ts_node_is_null(port)) {
      behavior.port = text_of(port);
      behavior.port_span = span_of(port);
    }
    const TSNode effects = field(node, "effects");
    each_named_child(effects, [&](const TSNode& effect_node) {
      if (node_is(effect_node, "effect")) {
        behavior.effects.push_back(extract_effect(effect_node));
      }
    });
    return behavior;
  }

  Equation extract_equation(const TSNode& node) {
    Equation equation;
    equation.span = span_of(node);
    equation.var = text_of(field(node, "name"));
    std::string rhs_text = text_of(field(node, "rhs"));
    // Trim the surrounding whitespace captured by the raw token.
    const auto trim = [](std::string& text) {
      const auto not_space = [](unsigned char c) {
        return !std::isspace(c);
      };
      const auto first = std::find_if(text.begin(), text.end(), not_space);
      if (first == text.end()) {
        text.clear();
        return;
      }
      const auto last = std::find_if(text.rbegin(), text.rend(), not_space);
      text = std::string(first, last.base());
    };
    trim(rhs_text);
    equation.rhs_text = rhs_text;
    return equation;
  }

  CoupleDecl extract_couple(const TSNode& node) {
    CoupleDecl couple;
    couple.span = span_of(node);
    couple.from_model = text_of(field(node, "from_model"));
    couple.from_port = text_of(field(node, "from_port"));
    couple.to_model = text_of(field(node, "to_model"));
    couple.to_port = text_of(field(node, "to_port"));
    return couple;
  }

  Node extract_node(const TSNode& decl) {
    Node node;
    node.span = span_of(decl);
    node.kind = text_of(field(decl, "kind"));
    node.name = text_of(field(decl, "name"));
    node.name_span = span_of(field(decl, "name"));
    const TSNode body = field(decl, "body");
    each_named_child(body, [&](const TSNode& member) {
      if (node_is(member, "field")) {
        // `range = min..max` parses as a field node wrapping a range_field
        // (the grammar choice inlines it); extract it as a range.
        const TSNode inner = ts_node_named_child(member, 0);
        if (node_is(inner, "range_field")) {
          node.ranges.push_back(extract_range(inner));
        } else {
          node.fields.push_back(extract_field(member));
        }
      } else if (node_is(member, "range_field")) {
        node.ranges.push_back(extract_range(member));
      } else if (node_is(member, "variable_declaration")) {
        node.vars.push_back(extract_var_decl(member));
      } else if (node_is(member, "port_declaration")) {
        node.ports.push_back(extract_port(member));
      } else if (node_is(member, "behavior")) {
        node.behaviors.push_back(extract_behavior(member));
      } else if (node_is(member, "equation")) {
        node.equations.push_back(extract_equation(member));
      } else if (node_is(member, "couple_declaration")) {
        node.couplings.push_back(extract_couple(member));
      } else if (node_is(member, "declaration")) {
        node.children.push_back(extract_node(member));
      }
    });
    return node;
  }

  // experiment Node -> typed ExperimentDecl (fields are bare-identifier or
  // integer values; range carries min/max).
  ExperimentDecl extract_experiment(const Node& node) {
    ExperimentDecl experiment;
    experiment.span = node.span;
    experiment.name = node.name;
    experiment.name_span = node.name_span;
    for (const Field& field : node.fields) {
      if (field.name == "objective") {
        experiment.objective_count += 1;
        experiment.objective_span = field.value.span;
        if (field.value.kind == ValueKind::kIdentifier) {
          experiment.has_objective = true;
          experiment.objective = field.value.string_value;
        }
      } else if (field.name == "metric") {
        experiment.metric_count += 1;
        experiment.metric_span = field.value.span;
        if (field.value.kind == ValueKind::kIdentifier) {
          experiment.has_metric = true;
          experiment.metric = field.value.string_value;
        }
      } else if (field.name == "variable") {
        experiment.variable_count += 1;
        experiment.variable_span = field.value.span;
        if (field.value.kind == ValueKind::kIdentifier) {
          experiment.has_variable = true;
          experiment.variable = field.value.string_value;
        }
      } else if (field.name == "budget") {
        experiment.budget_count += 1;
        experiment.budget_span = field.value.span;
        if (field.value.kind == ValueKind::kInt) {
          experiment.has_budget = true;
          experiment.budget = field.value.int_value;
        }
      }
    }
    for (const RangeField& range : node.ranges) {
      experiment.range_count += 1;
      experiment.range_span = range.span;
      experiment.has_range = true;
      experiment.range_min = range.min;
      experiment.range_max = range.max;
    }
    return experiment;
  }

  const std::string& source_;
  std::vector<Diagnostic>& diagnostics_;
};

}  // namespace

const char* to_string(DistKind kind) {
  switch (kind) {
    case DistKind::kPoisson: return "poisson";
    case DistKind::kExponential: return "exponential";
    case DistKind::kNormal: return "normal";
    case DistKind::kConstant: return "constant";
  }
  return "unknown";
}

const Field* find_field(const Node& node, const char* name) {
  for (const Field& field : node.fields) {
    if (field.name == name) {
      return &field;
    }
  }
  return nullptr;
}

const VarDecl* find_var(const Node& node, const char* keyword,
                        const std::string& name) {
  for (const VarDecl& var : node.vars) {
    if (var.keyword == keyword && var.name == name) {
      return &var;
    }
  }
  return nullptr;
}

bool distribution_from_value(const Value& value, Distribution& out) {
  out.span = value.span;
  if (value.kind != ValueKind::kCall) {
    return false;
  }
  const auto args_as_doubles = [](const std::vector<Value>& args) {
    std::vector<double> out;
    for (const Value& arg : args) {
      if (arg.kind == ValueKind::kInt) {
        out.push_back(static_cast<double>(arg.int_value));
      } else if (arg.kind == ValueKind::kFloat) {
        out.push_back(arg.float_value);
      } else {
        return std::vector<double>{};
      }
    }
    return out;
  };
  if (value.call_name == "poisson" || value.call_name == "rate") {
    const std::vector<double> args = args_as_doubles(value.call_args);
    if (args.size() != 1) return false;
    out.kind = DistKind::kPoisson;
    out.params = args;
    return true;
  }
  if (value.call_name == "exponential") {
    const std::vector<double> args = args_as_doubles(value.call_args);
    if (args.size() != 1) return false;
    out.kind = DistKind::kExponential;
    out.params = args;
    return true;
  }
  if (value.call_name == "normal") {
    const std::vector<double> args = args_as_doubles(value.call_args);
    if (args.size() != 2) return false;
    out.kind = DistKind::kNormal;
    out.params = args;
    return true;
  }
  if (value.call_name == "constant") {
    const std::vector<double> args = args_as_doubles(value.call_args);
    if (args.size() != 1) return false;
    out.kind = DistKind::kConstant;
    out.params = args;
    return true;
  }
  return false;
}

bool fold_value(const Value& value, const ParamScope& scope, Value& out) {
  out = value;
  switch (value.kind) {
    case ValueKind::kBool:
    case ValueKind::kInt:
    case ValueKind::kFloat:
    case ValueKind::kString:
      return true;
    case ValueKind::kIdentifier: {
      FoldedValue resolved;
      if (!scope.lookup(value.string_value, resolved)) {
        return false;
      }
      out = Value{};
      out.span = value.span;
      out.kind = resolved.kind;
      out.bool_value = resolved.bool_value;
      out.int_value = resolved.int_value;
      out.float_value = resolved.float_value;
      out.string_value = resolved.string_value;
      return true;
    }
    case ValueKind::kCall: {
      Value folded;
      folded.kind = ValueKind::kCall;
      folded.call_name = value.call_name;
      folded.span = value.span;
      for (const Value& arg : value.call_args) {
        Value arg_out;
        if (!fold_value(arg, scope, arg_out)) {
          return false;
        }
        folded.call_args.push_back(std::move(arg_out));
      }
      out = std::move(folded);
      return true;
    }
    case ValueKind::kParen:
      return fold_value(value.operands.empty() ? value : value.operands[0],
                        scope, out);
    case ValueKind::kNegate: {
      if (value.operands.empty()) {
        return false;
      }
      Value operand;
      if (!fold_value(value.operands[0], scope, operand)) {
        return false;
      }
      out = Value{};
      out.span = value.span;
      if (operand.kind == ValueKind::kInt) {
        out.kind = ValueKind::kInt;
        out.int_value = -operand.int_value;
        return true;
      }
      if (operand.kind == ValueKind::kFloat) {
        out.kind = ValueKind::kFloat;
        out.float_value = -operand.float_value;
        return true;
      }
      return false;
    }
    case ValueKind::kAdd:
    case ValueKind::kSub:
    case ValueKind::kMul:
    case ValueKind::kDiv: {
      if (value.operands.size() != 2) {
        return false;
      }
      Value left;
      Value right;
      if (!fold_value(value.operands[0], scope, left) ||
          !fold_value(value.operands[1], scope, right)) {
        return false;
      }
      const bool both_int =
          left.kind == ValueKind::kInt && right.kind == ValueKind::kInt;
      const bool numeric =
          (left.kind == ValueKind::kInt || left.kind == ValueKind::kFloat) &&
          (right.kind == ValueKind::kInt || right.kind == ValueKind::kFloat);
      if (!numeric) {
        return false;
      }
      const double l =
          left.kind == ValueKind::kInt ? static_cast<double>(left.int_value)
                                       : left.float_value;
      const double r =
          right.kind == ValueKind::kInt ? static_cast<double>(right.int_value)
                                        : right.float_value;
      out = Value{};
      out.span = value.span;
      if (value.kind == ValueKind::kDiv) {
        if (r == 0.0) {
          return false;
        }
        out.kind = ValueKind::kFloat;
        out.float_value = l / r;
        return true;
      }
      if (both_int) {
        out.kind = ValueKind::kInt;
        switch (value.kind) {
          case ValueKind::kAdd: out.int_value = left.int_value + right.int_value; break;
          case ValueKind::kSub: out.int_value = left.int_value - right.int_value; break;
          case ValueKind::kMul: out.int_value = left.int_value * right.int_value; break;
          default: break;
        }
        return true;
      }
      out.kind = ValueKind::kFloat;
      switch (value.kind) {
        case ValueKind::kAdd: out.float_value = l + r; break;
        case ValueKind::kSub: out.float_value = l - r; break;
        case ValueKind::kMul: out.float_value = l * r; break;
        default: break;
      }
      return true;
    }
  }
  return false;
}

ParseOutput parse_source(const std::string& source, const std::string& path) {
  ParseOutput output;

  TSParser* parser = ts_parser_new();
  ts_parser_set_language(parser, tree_sitter_logicpilot());
  TSTree* tree = ts_parser_parse_string(
      parser, nullptr, source.c_str(), static_cast<uint32_t>(source.size()));
  ts_parser_delete(parser);

  if (tree == nullptr) {
    Diagnostic diagnostic;
    diagnostic.severity = Severity::kError;
    diagnostic.code = "LP0001";
    diagnostic.message = "syntax error: parser produced no tree";
    output.diagnostics.push_back(std::move(diagnostic));
    return output;
  }

  const TSNode root = ts_tree_root_node(tree);
  collect_syntax_errors(root, source, output.diagnostics);
  if (!output.diagnostics.empty()) {
    ts_tree_delete(tree);
    return output;
  }

  ModelAst model;
  Extractor extractor{source, output.diagnostics};
  if (extractor.extract_model(root, model) && output.diagnostics.empty()) {
    output.model = std::move(model);
  }
  ts_tree_delete(tree);
  (void)path;  // spans are path-relative; lpcli renders them with the path
  return output;
}

}  // namespace logicpilot::dsl
