/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 91
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 19
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 18
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_model = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_use = 5,
  anon_sym_EQ = 6,
  anon_sym_range = 7,
  anon_sym_DOT_DOT = 8,
  anon_sym_state = 9,
  anon_sym_param = 10,
  anon_sym_COLON = 11,
  anon_sym_in = 12,
  anon_sym_out = 13,
  anon_sym_inout = 14,
  sym_trigger = 15,
  anon_sym_SEMI = 16,
  anon_sym_COMMA = 17,
  anon_sym_emit = 18,
  anon_sym_d = 19,
  anon_sym_SLASHdt = 20,
  sym_rhs_text = 21,
  anon_sym_couple = 22,
  anon_sym_DOT = 23,
  anon_sym_DASH_GT = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  sym_string_literal = 27,
  anon_sym_LPAREN = 28,
  anon_sym_RPAREN = 29,
  aux_sym_integer_token1 = 30,
  aux_sym_float_token1 = 31,
  sym_comment = 32,
  sym_source_file = 33,
  sym_model_declaration = 34,
  sym_model_body = 35,
  sym__model_member = 36,
  sym_use_declaration = 37,
  sym_declaration = 38,
  sym_declaration_body = 39,
  sym__declaration_member = 40,
  sym_field = 41,
  sym_range_field = 42,
  sym_variable_declaration = 43,
  sym_type_name = 44,
  sym_port_declaration = 45,
  sym_behavior = 46,
  sym_effect_list = 47,
  sym_effect = 48,
  sym_assignment_effect = 49,
  sym_emit_effect = 50,
  sym_call_effect = 51,
  sym_equation = 52,
  sym_couple_declaration = 53,
  sym_value = 54,
  sym_value_literal = 55,
  sym_boolean_literal = 56,
  sym_call = 57,
  sym_argument_list = 58,
  sym__argument = 59,
  sym_integer = 60,
  sym_float = 61,
  aux_sym_model_body_repeat1 = 62,
  aux_sym_declaration_body_repeat1 = 63,
  aux_sym_effect_list_repeat1 = 64,
  aux_sym_argument_list_repeat1 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_model] = "model",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_use] = "use",
  [anon_sym_EQ] = "=",
  [anon_sym_range] = "range",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_state] = "state",
  [anon_sym_param] = "param",
  [anon_sym_COLON] = ":",
  [anon_sym_in] = "in",
  [anon_sym_out] = "out",
  [anon_sym_inout] = "inout",
  [sym_trigger] = "trigger",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_emit] = "emit",
  [anon_sym_d] = "d",
  [anon_sym_SLASHdt] = "/dt",
  [sym_rhs_text] = "rhs_text",
  [anon_sym_couple] = "couple",
  [anon_sym_DOT] = ".",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string_literal] = "string_literal",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_integer_token1] = "integer_token1",
  [aux_sym_float_token1] = "float_token1",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_model_declaration] = "model_declaration",
  [sym_model_body] = "model_body",
  [sym__model_member] = "_model_member",
  [sym_use_declaration] = "use_declaration",
  [sym_declaration] = "declaration",
  [sym_declaration_body] = "declaration_body",
  [sym__declaration_member] = "_declaration_member",
  [sym_field] = "field",
  [sym_range_field] = "range_field",
  [sym_variable_declaration] = "variable_declaration",
  [sym_type_name] = "type_name",
  [sym_port_declaration] = "port_declaration",
  [sym_behavior] = "behavior",
  [sym_effect_list] = "effect_list",
  [sym_effect] = "effect",
  [sym_assignment_effect] = "assignment_effect",
  [sym_emit_effect] = "emit_effect",
  [sym_call_effect] = "call_effect",
  [sym_equation] = "equation",
  [sym_couple_declaration] = "couple_declaration",
  [sym_value] = "value",
  [sym_value_literal] = "value_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_call] = "call",
  [sym_argument_list] = "argument_list",
  [sym__argument] = "_argument",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [aux_sym_model_body_repeat1] = "model_body_repeat1",
  [aux_sym_declaration_body_repeat1] = "declaration_body_repeat1",
  [aux_sym_effect_list_repeat1] = "effect_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_model] = anon_sym_model,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_range] = anon_sym_range,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_state] = anon_sym_state,
  [anon_sym_param] = anon_sym_param,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_out] = anon_sym_out,
  [anon_sym_inout] = anon_sym_inout,
  [sym_trigger] = sym_trigger,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_emit] = anon_sym_emit,
  [anon_sym_d] = anon_sym_d,
  [anon_sym_SLASHdt] = anon_sym_SLASHdt,
  [sym_rhs_text] = sym_rhs_text,
  [anon_sym_couple] = anon_sym_couple,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_integer_token1] = aux_sym_integer_token1,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_model_declaration] = sym_model_declaration,
  [sym_model_body] = sym_model_body,
  [sym__model_member] = sym__model_member,
  [sym_use_declaration] = sym_use_declaration,
  [sym_declaration] = sym_declaration,
  [sym_declaration_body] = sym_declaration_body,
  [sym__declaration_member] = sym__declaration_member,
  [sym_field] = sym_field,
  [sym_range_field] = sym_range_field,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_type_name] = sym_type_name,
  [sym_port_declaration] = sym_port_declaration,
  [sym_behavior] = sym_behavior,
  [sym_effect_list] = sym_effect_list,
  [sym_effect] = sym_effect,
  [sym_assignment_effect] = sym_assignment_effect,
  [sym_emit_effect] = sym_emit_effect,
  [sym_call_effect] = sym_call_effect,
  [sym_equation] = sym_equation,
  [sym_couple_declaration] = sym_couple_declaration,
  [sym_value] = sym_value,
  [sym_value_literal] = sym_value_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_call] = sym_call,
  [sym_argument_list] = sym_argument_list,
  [sym__argument] = sym__argument,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [aux_sym_model_body_repeat1] = aux_sym_model_body_repeat1,
  [aux_sym_declaration_body_repeat1] = aux_sym_declaration_body_repeat1,
  [aux_sym_effect_list_repeat1] = aux_sym_effect_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_model] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_range] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_state] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_param] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inout] = {
    .visible = true,
    .named = false,
  },
  [sym_trigger] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_emit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASHdt] = {
    .visible = true,
    .named = false,
  },
  [sym_rhs_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_couple] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_model_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_model_body] = {
    .visible = true,
    .named = true,
  },
  [sym__model_member] = {
    .visible = false,
    .named = true,
  },
  [sym_use_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_body] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration_member] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_range_field] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_port_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_behavior] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_list] = {
    .visible = true,
    .named = true,
  },
  [sym_effect] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_effect] = {
    .visible = true,
    .named = true,
  },
  [sym_emit_effect] = {
    .visible = true,
    .named = true,
  },
  [sym_call_effect] = {
    .visible = true,
    .named = true,
  },
  [sym_equation] = {
    .visible = true,
    .named = true,
  },
  [sym_couple_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_value_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_model_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_effect_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_args = 2,
  field_body = 3,
  field_effects = 4,
  field_from_model = 5,
  field_from_port = 6,
  field_handler = 7,
  field_kind = 8,
  field_library = 9,
  field_max = 10,
  field_min = 11,
  field_name = 12,
  field_port = 13,
  field_rhs = 14,
  field_to_model = 15,
  field_to_port = 16,
  field_trigger = 17,
  field_type = 18,
  field_value = 19,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_args] = "args",
  [field_body] = "body",
  [field_effects] = "effects",
  [field_from_model] = "from_model",
  [field_from_port] = "from_port",
  [field_handler] = "handler",
  [field_kind] = "kind",
  [field_library] = "library",
  [field_max] = "max",
  [field_min] = "min",
  [field_name] = "name",
  [field_port] = "port",
  [field_rhs] = "rhs",
  [field_to_model] = "to_model",
  [field_to_port] = "to_port",
  [field_trigger] = "trigger",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 3},
  [7] = {.index = 13, .length = 1},
  [8] = {.index = 14, .length = 1},
  [9] = {.index = 15, .length = 3},
  [10] = {.index = 18, .length = 2},
  [11] = {.index = 20, .length = 2},
  [12] = {.index = 22, .length = 2},
  [13] = {.index = 24, .length = 1},
  [14] = {.index = 25, .length = 2},
  [15] = {.index = 27, .length = 4},
  [16] = {.index = 31, .length = 2},
  [17] = {.index = 33, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_name, 1},
  [2] =
    {field_library, 1},
  [3] =
    {field_body, 2},
    {field_kind, 0},
    {field_name, 1},
  [6] =
    {field_name, 1},
    {field_value, 3},
  [8] =
    {field_effects, 1},
    {field_trigger, 0},
  [10] =
    {field_name, 1},
    {field_type, 3},
    {field_value, 5},
  [13] =
    {field_type, 2},
  [14] =
    {field_handler, 0},
  [15] =
    {field_effects, 2},
    {field_port, 1},
    {field_trigger, 0},
  [18] =
    {field_name, 0},
    {field_value, 2},
  [20] =
    {field_args, 2},
    {field_name, 0},
  [22] =
    {field_name, 1},
    {field_type, 3},
  [24] =
    {field_port, 1},
  [25] =
    {field_arg, 1},
    {field_handler, 0},
  [27] =
    {field_from_model, 1},
    {field_from_port, 3},
    {field_to_model, 5},
    {field_to_port, 7},
  [31] =
    {field_max, 4},
    {field_min, 2},
  [33] =
    {field_name, 1},
    {field_rhs, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 1,
        '(', 31,
        ')', 32,
        ',', 20,
        '-', 10,
        '.', 28,
        '/', 4,
        ':', 18,
        ';', 19,
        '=', 16,
        '{', 14,
        '}', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '}') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(9);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SLASHdt);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_rhs_text);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_rhs_text);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_rhs_text);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_rhs_text);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_rhs_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(17);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'c', 1,
        'd', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'm', 6,
        'o', 7,
        'p', 8,
        'r', 9,
        's', 10,
        't', 11,
        'u', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_d);
      END_STATE();
    case 3:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == '_') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(40);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 30:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_out);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'g') ADVANCE(44);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_emit);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_trigger);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      if (lookahead == 'm') ADVANCE(51);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_inout);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_model);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_param);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_range);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_state);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_couple);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 8},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 9},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_model] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_range] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_state] = ACTIONS(1),
    [anon_sym_param] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
    [anon_sym_inout] = ACTIONS(1),
    [sym_trigger] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_emit] = ACTIONS(1),
    [anon_sym_d] = ACTIONS(1),
    [anon_sym_SLASHdt] = ACTIONS(1),
    [anon_sym_couple] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_integer_token1] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(86),
    [sym_model_declaration] = STATE(89),
    [anon_sym_model] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_RBRACE,
    ACTIONS(11), 1,
      anon_sym_range,
    ACTIONS(17), 1,
      sym_trigger,
    ACTIONS(19), 1,
      anon_sym_d,
    ACTIONS(21), 1,
      anon_sym_couple,
    STATE(32), 1,
      sym_range_field,
    ACTIONS(13), 2,
      anon_sym_state,
      anon_sym_param,
    ACTIONS(15), 3,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
    STATE(3), 9,
      sym_declaration,
      sym__declaration_member,
      sym_field,
      sym_variable_declaration,
      sym_port_declaration,
      sym_behavior,
      sym_equation,
      sym_couple_declaration,
      aux_sym_declaration_body_repeat1,
  [45] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_range,
    ACTIONS(17), 1,
      sym_trigger,
    ACTIONS(19), 1,
      anon_sym_d,
    ACTIONS(21), 1,
      anon_sym_couple,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      sym_range_field,
    ACTIONS(13), 2,
      anon_sym_state,
      anon_sym_param,
    ACTIONS(15), 3,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
    STATE(4), 9,
      sym_declaration,
      sym__declaration_member,
      sym_field,
      sym_variable_declaration,
      sym_port_declaration,
      sym_behavior,
      sym_equation,
      sym_couple_declaration,
      aux_sym_declaration_body_repeat1,
  [90] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(28), 1,
      anon_sym_RBRACE,
    ACTIONS(30), 1,
      anon_sym_range,
    ACTIONS(39), 1,
      sym_trigger,
    ACTIONS(42), 1,
      anon_sym_d,
    ACTIONS(45), 1,
      anon_sym_couple,
    STATE(32), 1,
      sym_range_field,
    ACTIONS(33), 2,
      anon_sym_state,
      anon_sym_param,
    ACTIONS(36), 3,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
    STATE(4), 9,
      sym_declaration,
      sym__declaration_member,
      sym_field,
      sym_variable_declaration,
      sym_port_declaration,
      sym_behavior,
      sym_equation,
      sym_couple_declaration,
      aux_sym_declaration_body_repeat1,
  [135] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 6,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
      sym_trigger,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(48), 11,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_emit,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [160] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 5,
      anon_sym_RBRACE,
      sym_trigger,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(52), 11,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_emit,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [184] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 4,
      anon_sym_RBRACE,
      sym_trigger,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(56), 11,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_emit,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 4,
      anon_sym_RBRACE,
      sym_trigger,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(62), 11,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_emit,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [233] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 4,
      anon_sym_RBRACE,
      sym_trigger,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(56), 11,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_emit,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [256] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 4,
      anon_sym_RBRACE,
      sym_trigger,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(66), 11,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_emit,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [279] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 4,
      anon_sym_RBRACE,
      sym_trigger,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(70), 11,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_emit,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [302] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(74), 10,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [322] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(78), 10,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [342] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 3,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_trigger,
    ACTIONS(82), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(86), 10,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [382] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 1,
      anon_sym_use,
    ACTIONS(101), 1,
      anon_sym_couple,
    ACTIONS(98), 2,
      anon_sym_state,
      anon_sym_param,
    STATE(16), 6,
      sym__model_member,
      sym_use_declaration,
      sym_declaration,
      sym_variable_declaration,
      sym_couple_declaration,
      aux_sym_model_body_repeat1,
  [410] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_identifier,
    ACTIONS(108), 1,
      sym_string_literal,
    ACTIONS(110), 1,
      aux_sym_integer_token1,
    ACTIONS(112), 1,
      aux_sym_float_token1,
    STATE(21), 1,
      sym_value,
    ACTIONS(106), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_value_literal,
      sym_call,
    STATE(10), 3,
      sym_boolean_literal,
      sym_integer,
      sym_float,
  [442] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_identifier,
    ACTIONS(108), 1,
      sym_string_literal,
    ACTIONS(110), 1,
      aux_sym_integer_token1,
    ACTIONS(112), 1,
      aux_sym_float_token1,
    STATE(29), 1,
      sym_value,
    ACTIONS(106), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_value_literal,
      sym_call,
    STATE(10), 3,
      sym_boolean_literal,
      sym_integer,
      sym_float,
  [474] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_identifier,
    ACTIONS(108), 1,
      sym_string_literal,
    ACTIONS(110), 1,
      aux_sym_integer_token1,
    ACTIONS(112), 1,
      aux_sym_float_token1,
    STATE(24), 1,
      sym_value,
    ACTIONS(106), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_value_literal,
      sym_call,
    STATE(10), 3,
      sym_boolean_literal,
      sym_integer,
      sym_float,
  [506] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_couple,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 1,
      anon_sym_use,
    ACTIONS(13), 2,
      anon_sym_state,
      anon_sym_param,
    STATE(16), 6,
      sym__model_member,
      sym_use_declaration,
      sym_declaration,
      sym_variable_declaration,
      sym_couple_declaration,
      aux_sym_model_body_repeat1,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(120), 10,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [554] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(124), 10,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [574] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_identifier,
    ACTIONS(108), 1,
      sym_string_literal,
    ACTIONS(110), 1,
      aux_sym_integer_token1,
    ACTIONS(112), 1,
      aux_sym_float_token1,
    STATE(47), 1,
      sym_value,
    ACTIONS(106), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_value_literal,
      sym_call,
    STATE(10), 3,
      sym_boolean_literal,
      sym_integer,
      sym_float,
  [606] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(128), 10,
      anon_sym_use,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [626] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_couple,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(118), 1,
      anon_sym_use,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_state,
      anon_sym_param,
    STATE(20), 6,
      sym__model_member,
      sym_use_declaration,
      sym_declaration,
      sym_variable_declaration,
      sym_couple_declaration,
      aux_sym_model_body_repeat1,
  [654] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(134), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [673] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(138), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [692] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(142), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [711] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(146), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [730] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(150), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [749] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(154), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(158), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(162), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [806] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(166), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [825] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_RBRACE,
      sym_trigger,
    ACTIONS(170), 9,
      anon_sym_range,
      anon_sym_state,
      anon_sym_param,
      anon_sym_in,
      anon_sym_out,
      anon_sym_inout,
      anon_sym_d,
      anon_sym_couple,
      sym_identifier,
  [844] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    ACTIONS(178), 1,
      anon_sym_emit,
    STATE(38), 1,
      aux_sym_effect_list_repeat1,
    STATE(43), 1,
      sym_effect,
    STATE(42), 3,
      sym_assignment_effect,
      sym_emit_effect,
      sym_call_effect,
  [868] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_emit,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      aux_sym_effect_list_repeat1,
    STATE(43), 1,
      sym_effect,
    STATE(42), 3,
      sym_assignment_effect,
      sym_emit_effect,
      sym_call_effect,
  [892] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_identifier,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    ACTIONS(187), 1,
      anon_sym_emit,
    STATE(38), 1,
      aux_sym_effect_list_repeat1,
    STATE(43), 1,
      sym_effect,
    STATE(42), 3,
      sym_assignment_effect,
      sym_emit_effect,
      sym_call_effect,
  [916] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(194), 1,
      anon_sym_EQ,
    ACTIONS(196), 1,
      anon_sym_emit,
    ACTIONS(192), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [934] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    ACTIONS(198), 5,
      anon_sym_use,
      anon_sym_state,
      anon_sym_param,
      anon_sym_couple,
      sym_identifier,
  [948] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_integer_token1,
    ACTIONS(112), 1,
      aux_sym_float_token1,
    STATE(74), 1,
      sym_argument_list,
    STATE(49), 3,
      sym__argument,
      sym_integer,
      sym_float,
  [966] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 2,
      anon_sym_emit,
      sym_identifier,
    ACTIONS(204), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [979] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    ACTIONS(206), 2,
      anon_sym_emit,
      sym_identifier,
    ACTIONS(210), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [994] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_integer_token1,
    ACTIONS(112), 1,
      aux_sym_float_token1,
    STATE(62), 3,
      sym__argument,
      sym_integer,
      sym_float,
  [1009] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 2,
      anon_sym_emit,
      sym_identifier,
    ACTIONS(214), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1022] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 2,
      anon_sym_emit,
      sym_identifier,
    ACTIONS(218), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1035] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 2,
      anon_sym_emit,
      sym_identifier,
    ACTIONS(222), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1048] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    ACTIONS(224), 2,
      anon_sym_emit,
      sym_identifier,
  [1059] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_argument_list_repeat1,
  [1072] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_argument_list_repeat1,
  [1085] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_identifier,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_effect_list,
  [1098] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_argument_list_repeat1,
  [1111] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_effect_list,
  [1121] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(30), 1,
      sym_type_name,
  [1131] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_identifier,
    ACTIONS(245), 1,
      anon_sym_COLON,
  [1141] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_EQ,
    ACTIONS(249), 1,
      anon_sym_COLON,
  [1151] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_declaration_body,
  [1161] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      aux_sym_integer_token1,
    STATE(34), 1,
      sym_integer,
  [1171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(257), 1,
      anon_sym_EQ,
  [1181] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_LBRACE,
    STATE(76), 1,
      sym_model_body,
  [1191] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(68), 1,
      sym_type_name,
  [1201] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1209] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      aux_sym_integer_token1,
    STATE(81), 1,
      sym_integer,
  [1219] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(27), 1,
      sym_type_name,
  [1229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_DASH_GT,
  [1236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
  [1243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_DOT,
  [1250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_EQ,
  [1257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_identifier,
  [1264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_EQ,
  [1271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym_identifier,
  [1278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_EQ,
  [1285] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_identifier,
  [1292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
  [1299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identifier,
  [1306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      ts_builtin_sym_end,
  [1313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_identifier,
  [1320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym_identifier,
  [1327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_DOT,
  [1334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      ts_builtin_sym_end,
  [1341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_DOT_DOT,
  [1348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      sym_identifier,
  [1355] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_identifier,
  [1362] = 2,
    ACTIONS(297), 1,
      sym_rhs_text,
    ACTIONS(299), 1,
      sym_comment,
  [1369] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_SLASHdt,
  [1376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      ts_builtin_sym_end,
  [1383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      sym_identifier,
  [1390] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      sym_identifier,
  [1397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
  [1404] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 160,
  [SMALL_STATE(7)] = 184,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 233,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 279,
  [SMALL_STATE(12)] = 302,
  [SMALL_STATE(13)] = 322,
  [SMALL_STATE(14)] = 342,
  [SMALL_STATE(15)] = 362,
  [SMALL_STATE(16)] = 382,
  [SMALL_STATE(17)] = 410,
  [SMALL_STATE(18)] = 442,
  [SMALL_STATE(19)] = 474,
  [SMALL_STATE(20)] = 506,
  [SMALL_STATE(21)] = 534,
  [SMALL_STATE(22)] = 554,
  [SMALL_STATE(23)] = 574,
  [SMALL_STATE(24)] = 606,
  [SMALL_STATE(25)] = 626,
  [SMALL_STATE(26)] = 654,
  [SMALL_STATE(27)] = 673,
  [SMALL_STATE(28)] = 692,
  [SMALL_STATE(29)] = 711,
  [SMALL_STATE(30)] = 730,
  [SMALL_STATE(31)] = 749,
  [SMALL_STATE(32)] = 768,
  [SMALL_STATE(33)] = 787,
  [SMALL_STATE(34)] = 806,
  [SMALL_STATE(35)] = 825,
  [SMALL_STATE(36)] = 844,
  [SMALL_STATE(37)] = 868,
  [SMALL_STATE(38)] = 892,
  [SMALL_STATE(39)] = 916,
  [SMALL_STATE(40)] = 934,
  [SMALL_STATE(41)] = 948,
  [SMALL_STATE(42)] = 966,
  [SMALL_STATE(43)] = 979,
  [SMALL_STATE(44)] = 994,
  [SMALL_STATE(45)] = 1009,
  [SMALL_STATE(46)] = 1022,
  [SMALL_STATE(47)] = 1035,
  [SMALL_STATE(48)] = 1048,
  [SMALL_STATE(49)] = 1059,
  [SMALL_STATE(50)] = 1072,
  [SMALL_STATE(51)] = 1085,
  [SMALL_STATE(52)] = 1098,
  [SMALL_STATE(53)] = 1111,
  [SMALL_STATE(54)] = 1121,
  [SMALL_STATE(55)] = 1131,
  [SMALL_STATE(56)] = 1141,
  [SMALL_STATE(57)] = 1151,
  [SMALL_STATE(58)] = 1161,
  [SMALL_STATE(59)] = 1171,
  [SMALL_STATE(60)] = 1181,
  [SMALL_STATE(61)] = 1191,
  [SMALL_STATE(62)] = 1201,
  [SMALL_STATE(63)] = 1209,
  [SMALL_STATE(64)] = 1219,
  [SMALL_STATE(65)] = 1229,
  [SMALL_STATE(66)] = 1236,
  [SMALL_STATE(67)] = 1243,
  [SMALL_STATE(68)] = 1250,
  [SMALL_STATE(69)] = 1257,
  [SMALL_STATE(70)] = 1264,
  [SMALL_STATE(71)] = 1271,
  [SMALL_STATE(72)] = 1278,
  [SMALL_STATE(73)] = 1285,
  [SMALL_STATE(74)] = 1292,
  [SMALL_STATE(75)] = 1299,
  [SMALL_STATE(76)] = 1306,
  [SMALL_STATE(77)] = 1313,
  [SMALL_STATE(78)] = 1320,
  [SMALL_STATE(79)] = 1327,
  [SMALL_STATE(80)] = 1334,
  [SMALL_STATE(81)] = 1341,
  [SMALL_STATE(82)] = 1348,
  [SMALL_STATE(83)] = 1355,
  [SMALL_STATE(84)] = 1362,
  [SMALL_STATE(85)] = 1369,
  [SMALL_STATE(86)] = 1376,
  [SMALL_STATE(87)] = 1383,
  [SMALL_STATE(88)] = 1390,
  [SMALL_STATE(89)] = 1397,
  [SMALL_STATE(90)] = 1404,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_declaration_body_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_literal, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_literal, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 11),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 11),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_body, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_body, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_couple_declaration, 8, 0, 15),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_couple_declaration, 8, 0, 15),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_name, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_body, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_body, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 6, 0, 6),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 6, 0, 6),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 3, 0, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 3),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, 0, 4),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 4),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_behavior, 3, 0, 9),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_behavior, 3, 0, 9),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 3, 0, 7),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 3, 0, 7),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_effect_list, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_list, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 10),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 10),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 4, 0, 12),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 4, 0, 12),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_behavior, 2, 0, 5),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_behavior, 2, 0, 5),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_effect_list, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_list, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_field, 5, 0, 16),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_field, 5, 0, 16),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equation, 5, 0, 17),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equation, 5, 0, 17),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [182] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_effect_list_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_effect_list_repeat1, 2, 0, 0),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_effect_list_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_effect, 1, 0, 8),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_effect, 1, 0, 8),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_declaration, 2, 0, 2),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_declaration, 2, 0, 2),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_effect, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_effect_list_repeat1, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_effect_list_repeat1, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emit_effect, 2, 0, 13),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emit_effect, 2, 0, 13),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_effect, 2, 0, 14),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_effect, 2, 0, 14),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_effect, 3, 0, 10),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_effect, 3, 0, 10),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_effect_list_repeat1, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_body, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_declaration, 3, 0, 1),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_body, 3, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [303] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_logicpilot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "logicpilot",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
